---
title: "Analysis of government trust and attitudes to vaccines"
author: "Daniel Allington"
date: "3/31/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(readr)
library(ggplot2)
library(knitr)
library(psych)

options(scipen = 999)

ed_levels <- c(
  "Primary school",
  "Secondary school (age under 15 years old)",
  "GNVQ / GSVQ / GCSE/ SCE standard.",
  "NVQ1, NVQ2",
  "NVQ3/ SCE Higher Grade/ Advanced GNVQ/ GCE A/AS or similar.",
  "NVQ4 / HNC / HND / Bachelor's degree or similar.",
  "NVQ5 or post-graduate diploma."                             
)

likert_levels <- c(
  "Strongly disagree", 
  "Tend to disagree", 
  "Neither agree nor disagree", 
  "Tend to agree", 
  "Strongly agree")                                

d_trustvac <- read_csv(
  '../data/trust-vaccines.csv',
  col_types = cols(
    col_number(),
    col_factor(),
    col_factor(ordered = TRUE, levels = ed_levels),
    col_factor(ordered = TRUE, levels = likert_levels),
    col_factor(ordered = TRUE, levels = likert_levels),
    col_factor(ordered = TRUE, levels = likert_levels),
    col_factor(ordered = TRUE, levels = likert_levels),
    col_factor(ordered = TRUE, levels = likert_levels),
    col_factor(ordered = TRUE, levels = likert_levels),
    col_factor(ordered = TRUE, levels = likert_levels),
    col_factor(ordered = TRUE, levels = likert_levels),
    col_factor(ordered = TRUE, levels = likert_levels)
  ))

d_trustvac <- d_trustvac %>%
  mutate(
    across(
      .cols = c(starts_with('gov'), starts_with('vac')),
      .fns = as.numeric,
      .names = '{.col}_coded'
    )
  )

keys_list <- list(
  gov_trust = c(
    'govhonest_coded',
    'govright_coded',
    '-govunfair_coded',
    '-govignore_coded',
    '-govcautious_coded',
    '-govxbel_coded'
  ),
  vac_attitude = c(
    'vacch_coded',
    'vacsafe_coded',
    'vacwork_coded'
  )
)

trustvac_scores <- scoreItems(
  keys = keys_list,
  items = d_trustvac,
  totals = FALSE,
  missing = TRUE,
  impute = 'none'
)

d_trustvac <- cbind(d_trustvac, trustvac_scores$scores)

```

# Demographic characteristics of the sample

## Age
```{r}
d_trustvac %>%
  summarise(
    n = n(),
    M = mean(age) %>% round(digits = 2), 
    Mdn = median(age),
    SD = sd(age) %>% round(digits = 2))

d_trustvac %>%
  ggplot(aes(x = age)) +
  geom_histogram(binwidth = 5)
```

## Gender
```{r}
d_trustvac %>%
  count(gender_nb)

d_trustvac %>%
  ggplot(aes(x = gender_nb)) +
  geom_bar()
```

## Highest educational qualifications
```{r}
d_trustvac %>%
  count(hhedqual)

d_trustvac %>%
  ggplot(aes(x = hhedqual)) +
  geom_bar() +
  coord_flip()
```

# Descriptive statistics: Likert items
```{r}
trustvac_likert_summary <- d_trustvac %>%
  select(ends_with('_coded')) %>%
  lapply(
    median, na.rm = TRUE
  )

d_trustvac_likert_summary <- tibble(
  Item = trustvac_likert_summary %>% names,
  Median = trustvac_likert_summary %>% unlist
)

d_trustvac_likert_summary

d_trustvac_likert_summary %>%
  ggplot(
    aes(x = Item, y = Median)
  ) +
  geom_point() +
  coord_flip()
```

```{r}

d_trustvac <- d_trustvac %>%
  mutate(
    Female = gender_nb == 'Female',
    Vaccines_safe = vacsafe %>%
      recode(
        'Strongly agree' = TRUE,
        'Tend to agree' = TRUE,
        'Neither agree nor disagree' = FALSE,
        'Tend to disagree' = FALSE,
        'Strongly disagree' = FALSE
      )
  )

d_trustvac %>%
  xtabs(~ Female + Vaccines_safe, .)

d_trustvac %>%
  group_by(Female) %>%
  summarise(
    n = n(),
    Agree = sum(Vaccines_safe, na.rm = TRUE)
  ) %>%
  mutate(
    Percentage = round(Agree / n * 100)
  )

chisq.test(
  d_trustvac$Female,
  d_trustvac$Vaccines_safe
)

fisher.test(
  d_trustvac$Female,
  d_trustvac$Vaccines_safe
)
```

```{r}
d_trustvac %>%
  wilcox.test(
    vacsafe_coded ~ Female,
    data = .
  )
```

```{r}
d_trustvac %>%
  t.test(
    age ~ Vaccines_safe,
    var.equal = FALSE,
    data = .
  )
```




